// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD84IB-XNAB23-23LMOy6wyA1TEyCOrIJk',
    appId: '1:575373742180:web:d48804b4d904abb3d9cf71',
    messagingSenderId: '575373742180',
    projectId: 'webback-fb243',
    authDomain: 'webback-fb243.firebaseapp.com',
    storageBucket: 'webback-fb243.appspot.com',
    measurementId: 'G-NGDJXF0TT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2nhNhKWjch4MTY3y8JB5qIgS-BfoM2q8',
    appId: '1:575373742180:android:64a2e531f2bf9fd1d9cf71',
    messagingSenderId: '575373742180',
    projectId: 'webback-fb243',
    storageBucket: 'webback-fb243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcCHExCwHDSinFNz75Vs4IgYHPw1u6gc',
    appId: '1:575373742180:ios:101e587f6fb67f74d9cf71',
    messagingSenderId: '575373742180',
    projectId: 'webback-fb243',
    storageBucket: 'webback-fb243.appspot.com',
    iosBundleId: 'com.example.controleAluguel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcCHExCwHDSinFNz75Vs4IgYHPw1u6gc',
    appId: '1:575373742180:ios:835cec33ce8d7d70d9cf71',
    messagingSenderId: '575373742180',
    projectId: 'webback-fb243',
    storageBucket: 'webback-fb243.appspot.com',
    iosBundleId: 'com.example.controleAluguel.RunnerTests',
  );
}
